### ISSUE TITLE
Proposal: Remove PATCH frame endpoint.

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1218]
### Description
Our documentation describes this endpoint as follows:

    `PATCH /index/<index-name>/frame/<frame-name>/time-quantum`

    Changes the time quantum for the given frame. This endpoint should be called at most once right after creating a frame.

Since it is possible to set the time quantum in the frame POST, and setting after frame creation is only allowed if there is no data in the frame, this endpoint seems to add confusion without value. Does anyone know the use case for creating the frame and setting up the time quantum in separate requests? Is it significant enough to warrant having this extra endpoint rather than just deleting and recreating the frame with the correct time quantum?

**Comment by travisturner** [comment]
```This endpoint should be called at most once right after creating a frame.```
That statement doesn't make sense to me.

In theory, one could change the time quantum on a frame at any time. Data written after the change will conform to the new timeQuantum. Queries performed after the change will return any available data based on the new timeQuantum.

So I don't think the reason we remove this should be because there is only a single point at which it makes sense to change the timeQuantum. But I do think it's fair for us to remove this based on the argument that it simplifies the API; we can just make clear in the documentation that changing the timeQuantum is not supported. And we can always bring it back later if we find users really need that feature.
