### ISSUE TITLE
Add schema info to /index/<indexname> endpoint

### ISSUE THREAD

**Issue by alanbernstein** [pilosa/pilosa#1283]
### Expected behavior
`GET /index/indexname` response includes some schema info and/or metadata about the index, as expected based on https://www.pilosa.com/docs/latest/api-reference/.

Example from docs:
`{"index":{"name":"user"}, "frames":[{"name":"collab"}]}]}`

### Actual behavior
Response is `{"index":{"name":"user"}}`, which provides no information except the name which is already known. This does verify that the index exists, but returning the schema/metadata is more useful.

I think this behavior was broken a while ago as part of some handler changes.

**Comment by jaffee** [comment]
@alanbernstein and @tgruben and I just discussed this. 

We think that making the response the same as the /schema response (but with only the requested index) in the list will be the best way to go here.

In the future we might want to support some kind of prefix based index fetching where a query might return multiple indexes, so keeping the exact same response structure as /schema seems like the simplest thing.

**Comment by jaffee** [comment]
I take it back -

since the /schema endpoint behaves identically to /index, we can reserve `/schema/<x>` for future prefix matching functionality, and make `/index/<indexname>` return just the index entry from the list of indexes which is returned by `/schema`. Similarly `/index/<indexname>/field/<fieldname>` should return just the field, and `/index/<indexname>/field` should return the list of fields for that index.
