### ISSUE TITLE
Client API thoughts

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#1368]
### Description
Having used it for quite some time, I'm not convinced that the ORM style of our client libraries lends itself to good ease of use or is particularly easy to get started with. The Go library in particular requires copious amounts of verbose error handling and boilerplate before one can begin actually making queries. This may just not be the way my brain works, and I'd love feedback, but I'm going to propose an alternate design that follows PQL more closely.

Here is an example of what using this alternative might look like for Go (I've shortened go-pilosa to 'pi'):
```go
// Get client
client, err := pi.NewClient("localhost:10101")
if err != nil {
	return errors.Wrap(err, "getting new client")
}

// Setting Stuff
resp, err := client.Queries("indexname",
	pi.Set("stargazer", 1, 2),
	pi.SetInt("intfield", 2, 27354),
	pi.SetWithTime("stargazer", 2, 3, time.Now()),
	pi.SetRowAttrs("field", 3, pi.Attr("aname", "aval"), pi.Attr("aname", "aval")),
	pi.SetColumnAttrs("field", 1, pi.Attr("aname", "aval"), pi.AttrInt("aname", 99)),
)
if err != nil {
	return errors.Wrap(err, "failed query")
}
// Nested Query
resp, err = client.Query("indexname", pi.Intersect( // TODO what is resp?
	pi.Row("fieldname", 1),
	pi.Row("otherfield", 2),
	pi.Union(
		pi.Row("field1", 7),
		pi.Row("field1", 9),
	)))
// Aggregates
resp, err = client.Queries("indexname",
	pi.Max("fieldint", nil),
	pi.Max("fieldint", Row("field1", 3)),
	pi.Min("fieldint", nil),
	pi.Sum("fieldint", nil),
)

// Ranges
resp, err = client.Queries("idnexname",
	pi.Between("field1", 0, 284),
	pi.GT("field1", 0),
	pi.GTE("field1", 0),
	pi.LT("field1", 0),
	pi.LTE("field1", 0),
	pi.NotEquals("field1", 0),
	pi.NotNull("field1"),
)

// TopN
resp, err = client.Queries("indexname",
	TopN("field", 0, Row()),
	TopNFiltered("field", 0, Row(), "fieldname", []string{"filterval1", "filterval2"}),
)

err := client.Import("indexname", "fieldname", iterator, OptImportBatchSize(1000000))

// Create index/frames
created, err := client.CreateIndex("indexname")
if err != nil {
	return errors.Wrap(err, "problem creating index")
}
if !created {
	return errors.New("indexname already exists")
}

_, err = client.CreateField("indexname", "fieldname", OptFieldSet(50000))
if err != nil {
	return errors.Wrap(err, "creating field")
}
// client.Delete[Index/Field]

```

and here are some potential interfaces and signatures from go-pilosa that were used above

```go
func SetRowAttrs(field string, row uint64, attrs ...Attr) Query
func SetColumnAttrs(field string, column uint64, attrs ...Attr) Query
```

Thoughts?

### Success criteria (What criteria will consider this ticket closeable?)
Make client libraries closer to PQL, easier to use, and reduce the verbosity in their use.

**Comment by yuce** [comment]
I think most of the boilerplate in the current way is the code that deals with `error` returned from `Index` and `Frame`/`Field`. We may remove those:
```go
field1 := schema.Index("i1").Field("field1")
```

**Comment by travisturner** [comment]
The part that usually trips me up in the client is around `SyncSchema()`. It seems like overkill to lazily create indexes/fields locally, and then explicitly sync them to the server. Inevitably I get in a state where I have missed the `SyncSchema()` step and my query fails. So with that in mind, it seems like this proposal is addressing that by removing the need for the client to maintain a local copy of indexes and fields.

I suppose one thing this proposal would no longer support is multi-index batch queries. Previously, the index was associated to the field, now it's provided to the query. I don't have a problem with removing this capability, but I wanted to note it here.

**Comment by jaffee** [comment]
consider https://github.com/pilosa/pilosa/issues/1368 if we decide to undergo this work.

**Comment by yuce** [comment]
Although currently more setup is needed, less typing than this proposal is required when the number of queries increases actually . The client can figure out the index from a query, so no need to specify it for every query. Specifying an index or a field requires 2 extra chars (quotes) for each index and field. A programmer would probably assign the index/field names to variables anyway.

The real bolierplate comes from index/field validation. I am not happy with that too. Note that, other clients don't have this problem since they throw exceptions on validation errors. For the Go client I've opted for returning validation errors on index/field access/creation to be able to catch those errors as early as possible, but I agree it's (usually) too much.

Batch queries currently requires all queries refer to the same index but that easily be changed to support multiple indexes without breaking the API. By the way, I think it would be great to support queries with different indexes on the server side (I believe that would require only adding a single handler).

I think instead of trying to mimic PQL in the client-side API, we should try to encapsulate more in order to be able to change stuff without breaking user code. If the user wants to send raw PQL queries, they can easily do so with `index.RawQuery`.
