### ISSUE TITLE
Error building from source release

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#1373]
### Expected behavior

It should be possible to build the Pilosa binary from the source release.

### Actual behavior

Trying to `make` the Pilosa binary from the source release ends with failure.

### Steps to reproduce the behavior

1) `wget https://github.com/pilosa/pilosa/archive/v0.10.1.tar.gz`
2) `tar xf v0.10.1.tar.gz`
3) `cd pilosa-0.10.1/`
4) `make`

Results in:
```
fatal: not a git repository (or any parent up to mount point /home/yuce)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make require-dep
make[1]: Entering directory '/home/yuce/ramdisk/pilosa-0.10.1'
fatal: not a git repository (or any parent up to mount point /home/yuce)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Makefile:127: *** Build dependency "dep" not installed. To install, run `make install-dep` or `make install-build-deps`.  Stop.
make[1]: Leaving directory '/home/yuce/ramdisk/pilosa-0.10.1'
Makefile:27: recipe for target 'vendor' failed
make: *** [vendor] Error 2
```

**Comment by codysoyland** [comment]
The error text I get is different from what you are seeing, but the fix for me is to simply make a GOPATH and put the source into $GOPATH/src/github.com/pilosa/pilosa, and then I am able to compile a binary.

The source releases on Github are automatically generated when a tag is pushed. I imagine any Go project would have the same issue with not being buildable without setting up a Go environment. Our [installation instructions](https://www.pilosa.com/docs/latest/installation/#build-from-source) specify that you must put the source in a GOPATH, so I don't consider this a bug.
