### ISSUE TITLE
keys field are not supported in cluster?

### ISSUE THREAD

**Issue by zhyhang** [pilosa/pilosa#1545]
For bugs, please provide the following:

### Expected behavior

curl 192.168.155.107:10101/index/test3 -d '{"options": {"keys": true}}' 
curl 192.168.155.107:10101/index/test3/field/daat -d '{"options": {"keys": true}}' -X POST
curl 192.168.155.107:10101/index/test3/query -d 'Set("600001",daat="be9dc9de9a2c81e93d48658cc1ab2936")'

### Actual behavior
**above last line run error in 3 nodes cluster,  but in single server is OK.**

### Steps to reproduce the behavior
create 3 nodes cluster  
run above index/field/set cmds in  one connected node  
run above set cmd in another conntected node  

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
os:
CentOS 6.4  CPU 2U 12cores 64GB  
CentOS 7.2 CPU 2U 12cores   内存128GB

pilosa 1.0.1

config files:

node1
data-dir = "/data/pilosa/data" 
bind = "192.168.152.104:10101" 
log-path = "/data/pilosa/log" 
verbose = true 

[gossip] 
port = 12000 
seeds = ["192.168.152.104:12000", "192.168.155.107:12000"] 

[cluster] 
replicas = 1 
coordinator = true 
long-query-time = "1m0s" 

[handler] 
allowed-origins = ["http://192.168.155.107:8000"]
-------------------------------------------------------------------------------

node2
data-dir = "/data/pilosa/data" 
bind = "192.168.152.103:10101" 
log-path = "/data/pilosa/log" 
verbose = true 

[gossip] 
port = 12000 
seeds = ["192.168.152.104:12000", "192.168.155.107:12000"] 

[cluster] 
replicas = 1 
coordinator = false 
long-query-time = "1m0s" 

[handler] 
allowed-origins = ["http://192.168.155.107:8000"] 
-------------------------------------------------------------------------------

node3
data-dir = "/data/pilosa/data" 
bind = "192.168.155.107:10101" 
log-path = "/data/pilosa/log" 
verbose = true 

[gossip] 
port = 12000 
seeds = ["192.168.152.104:12000", "192.168.155.107:12000"] 

[cluster] 
replicas = 1 
coordinator = false 
long-query-time = "1m0s" 

[handler] 
allowed-origins = ["http://192.168.155.107:8000"]

For feature requests, please provide the following:

**Comment by codysoyland** [comment]
Thank you for the bug report, @zhyhang. I was able to reproduce this issue and can confirm that the string ID translator does not appear to be working on clusters at the moment. I will continue investigating and update this ticket as I learn more.

**Comment by codysoyland** [comment]
@zhyhang I believe this issue is addressed by #1552, which was also released today in version 1.0.2.

Note that the key translation currently is centralized on a single node and that all other nodes must be configured with `translation.primary-url` set to the address of that node, ie. `http://node0:10101/`. Furthermore, all writes (`Set()`) calls must be performed to that node. For now I recommend using your coordinator node as the translation primary node. We intend to eventually allow writes to non-primary nodes, but we are still working that out.

Please give 1.0.2 a try and let me know here if you have any further problems!
