### ISSUE TITLE
Suggestions of Pilosa for user profile big data system

### ISSUE THREAD

**Issue by zhyhang** [pilosa/pilosa#1553]
## We would like to use Pilosa for user profiling system. Are there some successful examples?

- We have 10 trillions users, and possible hundreds thousands tags of every user.  
- The design is every user id is a column, user's tags as rows.  
- Every day, writing about 100 millions users and 1 trillions tags of those users (update or insert).  
- Query with condition like:    
**(tag1 & (tag2 | tag3)) 's users**  
**(tag1 & (tag2 | tag3)) 's users count (best interactive query)** 
**(tag1 & (tag2 | tag3)) 's users another tags grouped count  (best interactive query)**
**a package (10 millions) of user's tags grouped count**
- Clean some users tags for a interval time, e.g. every week.

Would you give some suggestions?

Thanks.

**Comment by zhyhang** [comment]
Sorry. The user scale is not trillions, but 10 billions.
Not all users have 10k tags individual, max 10k tags of an user. average 100 tags.
"clean some users tags", I mean delete all tags of some users(clear all rows of some columns).
I plan to periodically delete users, decay users. What's efficient manner? 
The set of user will go to increase day after day, but deleting users day after day as well.

**Comment by travisturner** [comment]
Currently there's no way to delete everything pertaining to a column, short of sending a `Clear()` call to every row. We are actively working on a way to query all rows for a column (see #1482, #1496), and this could reasonably be used to clear all rows for a column.

We are also exploring ways to decay data by shard. This use case would be more like a time-series scenario, where new columns are added over time, and older columns are decayed based on some configuration. In order to do this, we're changing the way queries are distributed; instead of sending queries to all shards 0 to n, we will be able to selectively send queries to specific shards. That work is ongoing. As it stands now, you could delete the older shard files from disk, but you would need to stop Pilosa before deleting the files.

Finally, if you want to implement some kind of time-stamp with which to decay (or filter out) older columns, you could keep an integer field representing a day (for example, the number of days after 2018-01-01, so today would be 208) and populate that field on user creation. Then you could intersect queries  with `Range(days > 201)` to include only the last week of users.

Let us know if you end up trying anything like that. We're happy to help if you have questions or run into problems. And if there's any other functionality you'd like to see, definitely open up a github issue so we can track it and get it on the roadmap.

**Comment by zhyhang** [comment]
@travisturner Thank you!
As known, user profiling in big data is dramatically resource consuming system. We found Pilosa is a component fit for the case, because is high performance for store and query the data. We will try to achieve success with you.

**Comment by jaffee** [comment]
closing this, but feel free to reopen, or get in touch with us via slack or email if you'd like to discuss further! https://www.pilosa.com/community/#support

Thanks.
