### ISSUE TITLE
Improve primary TranslateStore configuration

### ISSUE THREAD

**Issue by travisturner** [pilosa/pilosa#1578]
### Description

We need to support at least one of two things:
1. clients can send keyed writes to any node in the cluster
2. clients can determine from the server which node should be sent keyed writes
There is a description of the issue that highlights this in #1577.
There is a bit of discussion around this in #1557.

Some suggestions that are related to a potential solution, but not necessarily related to or dependent upon each other are:
- automatically make the `cluster.Coordinator` the primary TranslateStore. Note that in this case it's not adequate to have all other nodes automatically point to the primary for replication; instead, additional node replication should be daisy-chained: node0 (primary) > node1 > node2, etc.
- if a keyed write is received by a non-primary node, it can forward the request to the primary
- keyed writes must always be sent to the primary node, but clients have a way to ask the server which node that is (if it's the case that the primary is the `cluster.Coordinator`, then that information is currently available in the `/status` endpoint)

**Comment by yuce** [comment]
The second option seems the be the most performant. The clients can ask one of the nodes in the cluster which node is the translator for an index, and they can cache the response. Of course that would require the same node is always the translator for an index.

What happens if a translator node goes down? Do we assign a new one or just reject keyed queries/imports ?
