### ISSUE TITLE
Restarted cluster coordinator gets stuck in state "Starting"

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1585]
### Expected behavior

Restarting any node should result in all nodes entering state `Normal` after nominal startup time.

### Actual behavior

Restarting cluster coordinator results in coordinator node staying in state `Starting` until other nodes are restarted.

### Steps to reproduce the behavior

1. Start a two-node cluster:

```
# shell 0
pilosa server --data-dir=/tmp/node0 --bind=localhost:10101 --gossip.port=14000 --gossip.seeds=localhost:14000 --cluster.coordinator=true

# shell 1
pilosa server --data-dir=/tmp/node1 --bind=localhost:10102 --gossip.port=14001 --gossip.seeds=localhost:14000
```

2. Restart node0 (in shell 0: ctrl-c, up-arrow, enter)

3. Check status of node0:
```
# curl localhost:10101/status
{"state":"STARTING","nodes":[{"id":"ea678131-9660-40e2-9005-944e8619082f","uri":{"scheme":"http","host":"localhost","port":10101},"isCoordinator":true}],"localID":"ea678131-9660-40e2-9005-944e8619082f"}
```

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Mac OS, pilosa master

**Comment by jaffee** [comment]
I think this is actually not solvable unless the coordinator stores information about other hosts that it finds through gossip and retrieves that information on startup. The problem is effectively that the coordinator is only gossip seeded to itself, so when it shuts down, the rest of the cluster forgets about it, and when it comes back up, it only tries to talk to itself to rejoin the cluster. The other nodes won't try to talk to it after it goes down unless they are restarted.

**Comment by jaffee** [comment]
the "workaround", or perhaps the correct way to configure a cluster (and perhaps our documentation needs to be updated) is to have the coordinator node seeded to other nodes in the cluster. We should confirm that this doesn't cause any issues though.

**Comment by jaffee** [comment]
The answer here is to make sure the coordinator has other nodes in the cluster as its seed. We could improve this with something like #900, but that would be an additional feature, not a bug.
