### ISSUE TITLE
Error: cannot allocate memory in tests (386)

### ISSUE THREAD

**Issue by codysoyland** [pilosa/pilosa#1604]
### Expected behavior

Test suite passes

### Actual behavior

Bombs out with error:
```pilosa.go:277: run cluster: starting cluster: starting server 0: opening server: cannot allocate memory```

### Steps to reproduce the behavior

This doesn't fail for everyone (for example it passes in TravisCI), but it happened in CircleCI (I'm trialing it on my personal fork), and I reproduced it on my Mac:

```GOARCH=386 GOCACHE=false go test -v github.com/pilosa/pilosa/test```

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Demonstrated in CircleCI here:
https://circleci.com/gh/codysoyland/pilosa/14

**Comment by benbjohnson** [comment]
32-bit systems only have 4GB of virtual address space (2^32) so `mmap` is unable to allocate more than that. In practice it usually can't allocate more than 2GB and even that could be tough if the address space is fragmented.

64-bit systems have 16 exabytes of virtual address space (2^64) so it never fails to find space in there for the mmap.

**Comment by codysoyland** [comment]
To elaborate on this ticket, the source of the error is in `translate.go`, line 111, in `TranslateFile.Open`:
```
syscall.Mmap(int(s.file.Fd()), 0, s.mapSize, syscall.PROT_READ, syscall.MAP_SHARED);
```
The value of `s.mapSize` is configured by a const that is unique to the architecture: 10GB on 64-bit and 2GB on 32-bit.

As Ben mentioned, it is impossible to allocate more than 4GB on 32-bit systems. This problem is compounded by the fact that multiple translate stores are instantiated by our test utilities.

In order to get CI tests to pass consistently on 32-bit, I had to change the deadline from `(1 << 31)` to roughly `(1 << 27)`. We would prefer not to lower this default, which is already too low for some use cases. For example, we also have issue #1546, in which one user is hitting the limit even on a 64-bit system.

@benbjohnson Would it make sense to allocate the memory-mapped file in blocks as needed? Is it possible to dynamically grow them? Or perhaps have a tiered data structure that is one `mmap` tracking _n_ other `mmap`s?

**Comment by benbjohnson** [comment]
@codysoyland Unfortunately allocating smaller chunks still doesn't work on 32-bit systems because 32-bits is the total addressable space. You may have more issues if you tried allocating multiple smaller chunks on 32-bit systems since you'll have more fragmentation and the OS won't be able to find continuous blocks of virtual memory.

re: #1546, it seems like we could solve that pretty easily by simply making the map size configurable. It would require a restart but that's part of the tradeoff for using mmaps. We could do multiple mmaps but I'm not sure the complexity is worth it when a simple config change would do the same thing.
