### ISSUE TITLE
feature: cross-Index queries would be super neat (Joins)

### ISSUE THREAD

**Issue by seebs** [pilosa/pilosa#1752]
### Description

In some cases, it makes sense to want to be able to use two separate indexes together in a query. There are in fact three fundamentally different cases where this makes sense, but for now I'm treating this as a single desireable goal.

The first case is that both indexes have the same column space, but different rows. In most cases, it would probably make sense to simply merge the rows into the same index, but there may be cases where this is inconvenient. (For instance, the indexes might be coming from different sources, and importing them separately is more convenient.) In this case, all you need is the ability to forward a query to another index, get a row back, and use that row. An existing hackathon implementation exists, called `IndexRow`. (https://github.com/pilosa/pilosa/pull/1704) This takes any valid row call, and an index, and yields the corresponding row. As long as the column spaces are the same, this is easy.

The more challenging case is where the column space in one index is a field in another index. This was brought up in the past (https://github.com/pilosa/pilosa/issues/1595).

With that in mind, I propose a hypothetical operation:

`IndexTransposedRow(ROW_CALL, field=fieldname, index=indexname)`

The semantics of this are:

1. A new all-zero row of unspecified size is created.
2. ROW_CALL is performed on the named index, yielding a row.
3. for each 1 bit in row, the named (BSI) field is looked up.
4. if the named field is non-null, the corresponding bit in the new row is set, possibly expanding that row.
5. the resulting row is returned.

Use case: Basically, foreign key joins. Consider the case of a table of events with corresponding user IDs, and users, with information about those users. The columns in the user table relate to field values in the event table. Thus, `IndexTransposedRow(..., field=userid, index=events)` would allow a query of users who had appeared in the events denoted.

It would also be desireable to be able to select entries where a given field is found in a range of columns. (This need not imply a distinct index.) Suggested syntax: Where we currently support `field > value`, we introduce a new comparison operator, IN, which can take an arbitrary ROW_CALL. This checks whether the given BSI field value is one of the columns with a 1 bit in the ROW_CALL. Since that call can be `IndexRow` or `IndexTransposedRow`, this allows essentially arbitrary lookups, including lookups in other indexes.

`field IN ...` is probably going to be innately fairly slow for largeish numbers of bits set. On the other hand, right now, the only way to do it is to do the first row query, get the column values, and then construct one or more queries and union them, so.

Given a hypothetical pair of indexes on user ids and events, `IndexTransposedRow(..., field=userid, index=events)` can be used in queries on users to find users who had specific events occur, and `userid IN IndexRow(.., index=users)` can be used in queries on events to find events associated with users matching particular criteria.

Neither allows the functionality of something more like an SQL JOIN operation, producing distinct values from both indexes, but my current understanding is that usually that kind of work would be handed off to another database, with Pilosa's role being to perform the initial computations and indexing more quickly.

### Success criteria (What criteria will consider this ticket closeable?)

Not sure yet. I think we should come up with some sample use cases, possibly things like fancy queries against one of the existing large data sets (the taxi trip data set looks appealing), comparing both the ease of expressing the queries, and also the performance of actually running them.

**Comment by travisturner** [comment]
This is an interesting proposal. I hadn't thought to use BSI (`int`) fields to store the foreign key value. I'd be curious to see how that performs. Some things we would need to consider:
- what would the default `bitDepth` be for the BSI field? making it 63, while allowing for a large column set, might significantly affect performance.
- since the size of the results from (2) ROW_CALL determines how many range queries would need to be performed on the BSI field, that could quickly become unreasonable at scale.

An alternative approach would be to track the foreign key relationship in a `mutex` (for one-to-many joins) or `set` (for many-to-many joins). The obvious problem with this is that we would effectively be mapping columns, which can grow without bound, to rows, which cannot. So unless/until we have a vialble row-scaling solution, this is problem not a reasonable approach. The only time I think this could work given pilosa's current abilities would be if one of the indexes was reasonable bounded (using your example, let's say the events index grew without bound, but the user index would never go over 1M).

Finally, in the case where two indexes have the same column space, it might be preferable to keep the two indexes separate (as opposed to collapsing their fields into one index) because currently all fields for a given index/shard are located on the same node. Separating fields into different indexes will better distribute those fragments across the cluster (with obvious performance implications).

**Comment by seebs** [comment]
I'm not sure what is a good bitDepth for the BSI field. Possibly "whatever the user needs to represent the column space they care about".

My guess is that even an atrociously slow thing that's basically a series of range queries on the BSI field would still be dramatically faster than doing the same thing by any less-direct method, such as by having users submit multiple queries. But also, it might admit optimizations of some sort to dramatically reduce those queries. Like, if we have values 0..15 in the list, we can just map that to "everything where all but the bottom four bits are zeroes".

So the idea isn't so much that `field in ...` will be very efficient, as that it might be less terrifyingly *in*efficient than anything else you could do in order to achieve those results.

TransposedRow is clearly a much easier case. `field in` is mostly interesting because, in the user/event table case, it makes sense to want a list of events more than you want a list of users. And you can just do the list of events, and the list of users, and then manually do the lookups... although that's complicated because there's no way to extract the user_id field in a query on the events table, right now. You can do range requests on it, but I don't think you can request results which map the event IDs to the user IDs, so you'd have to take your list of events back to some other database to do a join against users.

**Comment by jaffee** [comment]
Closing this pending work on a plugin framework upon which more advanced query capabilities will be built.
