### ISSUE TITLE
com.pilosa.client.exceptions.PilosaException: executing: column value must be a string when index 'keys' option enabled

### ISSUE THREAD

**Issue by MicDP** [pilosa/pilosa#1770]
I can't use the method 'public PqlBaseQuery set(String rowKey, long columnID) in Field class', How to do?

Index 'user' config:  
{"name":"user","options":{"keys":true},"fields":[{"name":"city","options":{"type":"set","cacheType":"ranked","cacheSize":50000,"keys":false}},{"name":"os","options":{"type":"set","cacheType":"ranked","cacheSize":50000,"keys":true}}]}

// client code for java
        IndexOptions indexOptions = IndexOptions.builder()
                .keys(false)
                .build();
        FieldOptions fieldOptions = FieldOptions.builder()
                .keys(false)
                .build();
        String fieldName = "os";
        Index user = schema.index("user", indexOptions);
        Field field = user.field(fieldName, fieldOptions);
        String rowKey = "win7";
        String columnKey = "12";
        long column = 12;
        client.query(field.set(rowKey, column));
        client.close();
// end

Then, it throws: 
com.pilosa.client.exceptions.PilosaException: executing: column value must be a string when index 'keys' option enabled

	at com.pilosa.client.PilosaClient.queryPath(PilosaClient.java:587)
	at com.pilosa.client.PilosaClient.query(PilosaClient.java:181)
	at com.pilosa.client.PilosaClient.query(PilosaClient.java:164)
	at com.wolaidai.demo.AppTest.writeColumnValue(AppTest.java:131)

**Comment by yuce** [comment]
Hi @MicDP, since you are using a row key, `keys` option of the `field` must be set to `true`:
```java
FieldOptions fieldOptions = FieldOptions.builder()
.keys(true)
.build();
```
Also, both index and field options are *sticky*, once you create an index or field with some options, they are retained by Pilosa. In the schema you have posted on the top, the index has `keys == true`, so a column key must be used. When you specify `keys(false)` in the code, it doesn't change what's on the server unless that index/field doesn't already exist.

Can you try deleting the `user` index using something like (with the correct Pilosa address):
```
curl localhost:10101/index/user -XDELETE
```

And running the following Java code based on yours:
```java
    public static void main(String...args) throws IOException {
        PilosaClient client = PilosaClient.defaultClient();
        Schema schema = Schema.defaultSchema();
        IndexOptions indexOptions = IndexOptions.builder()
                .keys(false)
                .build();
        FieldOptions fieldOptions = FieldOptions.builder()
                .keys(true)
                .build();
        String fieldName = "os";
        Index user = schema.index("user", indexOptions);
        Field field = user.field(fieldName, fieldOptions);
        client.syncSchema(schema);
        String rowKey = "win7";
        String columnKey = "12";
        long column = 12;
        client.query(field.set(rowKey, column));
        client.close();
}
```

Btw, the Java client has its own issue tracker at: https://github.com/pilosa/java-pilosa/issues

**Comment by MicDP** [comment]
@yuce it's OK! Thanks!

**Comment by yuce** [comment]
Awesome!
