### ISSUE TITLE
roaring.Bitmap.UnmarshalBinary - streaming variant

### ISSUE THREAD

**Issue by dmibor** [pilosa/pilosa#1850]
For feature requests, please provide the following:

### Description
Right now to unmarshal bitmap from file requires to read it all into memory - that proves to be the highest memory consumer when working with big bitmaps. Would be good if it would be possible to unmarshal binary from Reader
### Success criteria (What criteria will consider this ticket closeable?)
No need to read entire bitmap file into memory to unmarshal it

**Comment by jaffee** [comment]
just to be clear, the issue here seems to be that we're actually using double memory. There must be enough memory available to hold the whole bitmap file in memory, but when unmarshaling, it seems that we're needing twice that which can probably be fixed.

**Comment by dmibor** [comment]
yes, exactly, can say it this way too

**Comment by dmibor** [comment]
don't think it solves this issue completely - I still need to collect and pass []byte of the whole bitmap to UnmarshalBinary() to generate new bitmap from it. In this issue I wanted to check if it's possible to avoid reading whole bitmap file into []byte

**Comment by jaffee** [comment]
My initial thought was that we'd need to provide a streaming version of UnmarshalBinary that accepted an io.Reader, but @tgruben pointed out that this likely wouldn't help. This is because UnmarshalBinary keeps the data in the byte slice around and creates pointers into it at various places. The []byte passed to UnmarshalBinary is the same data *and the same memory* that gets used by the resultant bitmap.

Ingesting via /import-roaring though, there was a totally extraneous copy of the raw byte slice being made in api.ImportRoaring which we've now removed.

Going back through the heap profile you provided, it appears that the protobuf unmarshaling is also allocating a ridiculous amount of memory beyond the initial `ReadAll` in the handler. It's unclear to me why this is occurring, but it feels like a flaw in the generated protobuf code. I think that would be the next place to look if the current version is still causing memory issues. 

This is the handler which shows the (I think unavoidable) allocation of ioutil.ReadAll and the serializer Unmarshaling allocation which should be possible to get rid of:
```
         .          .   1572:	// Read entire body.
         .   293.27GB   1573:	body, err := ioutil.ReadAll(r.Body)
         .          .   1574:	if err != nil {
         .          .   1575:		http.Error(w, err.Error(), http.StatusBadRequest)
         .          .   1576:		return
         .          .   1577:	}
         .          .   1578:
         .          .   1579:	req := &pilosa.ImportRoaringRequest{}
         .   112.76GB   1580:	if err := h.api.Serializer.Unmarshal(body, req); err != nil {
         .          .   1581:		http.Error(w, err.Error(), http.StatusBadRequest)
         .          .   1582:		return
         .          .   1583:	}
         .          .   1584:
```

**Comment by dmibor** [comment]
> This is because UnmarshalBinary keeps the data in the byte slice around and creates pointers into it at various places. The []byte passed to UnmarshalBinary is the same data _and the same memory_ that gets used by the resultant bitmap.

Oh, got it. That what I wanted to check, was unclear if []byte was tossed out after bitmap is created or not. Then it's indeed as efficient as it can be here.

Interesting find about protobuf unmarshal! so much garbage is indeed surprising. Maybe we can continue looking at that in other thread related to load memory optimization. This thread was more about working with roaring.Bitmap outside of Pilosa
