### ISSUE TITLE
Rows() query with int field returns empty list

### ISSUE THREAD

**Issue by young118** [pilosa/pilosa#2123]
For bugs, please provide the following:

### What's going wrong?
Rows() query on int field returns empty list.the field is like this.
```
{
      "name": "count",
      "options": {
        "type": "int",
        "base": 1,
        "bitDepth": 6,
        "min": 1,
        "max": 200000,
        "keys": false
      }
},
```
when I query Rows(count), it returns 
```
{
  "results": [
    {
      "rows": []
    }
  ]
}
```
but when I query Row(count>2), a list of columns returned.I don't know if it's a bug or I did something wrong, please tell me why, thanks
### What was expected?
Rows(count) should return a list of rowID
### Steps to reproduce the behavior
I use python client to create the index, I create the field with this line `index.field("count", int_min=1, int_max=200000)`, then set some data into it
### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
ubuntu 18.04
4 core
8G
solo
default configuration

**Comment by travisturner** [comment]
@young118 the `Rows()` query isn't supported on `int` fields. On a `set` field, the `Rows()` query returns all the row ID of the bit matrix containing at least one set bit. Because of the way the `int` data is encoded in the bit matrix (using [bit-sliced indexes](https://www.pilosa.com/blog/range-encoded-bitmaps/)), it wouldn't be very useful to return the row IDs. The equivalent to the `Rows()` query on an `int` field would really be a function which returns the list of distinct values in the `int` field, but that doesn't exist either.

Is there something specific you're trying to get from the `int` field?

**Comment by young118** [comment]
I use pilosa to store network packet, so there are ip, mac, and port field. Ip mac is set field or time field, port is int filed.I want to calculate the count of distinct packet, so I do `GroupBy(Rows(ip), Rows(mac), Rows(port))`, and I just care the 0 ~ 1024 port，so the query will be `GroupBy(Rows(ip), Rows(mac), Rows(port), filter=Row(port<1024))`, how can I do that? Thanks

**Comment by jaffee** [comment]
you could actually have port be a set field and then in the GroupBy you could do `Rows(field=port, limit=1024)` which would give you what you want, I think. You lose the ability to to do range queries over port, but filtering by a single port is much faster.

**Comment by young118** [comment]
@jaffee  I tried, but the limit parameter limits the number returned, not the RowID. Will this work?,`GroupBy(Rows(ip), Rows(mac), Rows(port), filter=Union(Row(port=1), Row(port=2), ......Row(port1024)))`, will it harm the performance?

**Comment by jaffee** [comment]
If port is a `set` field with `keys: false`, then `Rows(field=port, limit=1025)` should give you ports 0-1024. It's kind of a hack, but it should work (though it will skip rows that have no data.. maybe that's what you're running into). You can also use the `previous` argument on `Rows` to start from a particular number. 

Your solution will work, but performance will be bad for two reasons. 
1. That Union will be a bit expensive to compute... but it only has to be done once, so not too bad.
2. The GroupBy will internally iterate through every combination of IP, MAC, and port, so will be quite slow even though most won't produce a result due to the filter.

**Comment by young118** [comment]
@jaffee thanks, I understand, another question, is GroupBy an expensive operation, and how many Rows will be too many for GroupBy?

**Comment by jaffee** [comment]
You can page through the results by using the previous and limit arguments on the `Rows` queries. The total possible number of results is the cardinality of all the fields multiplied together, so in your example, if you have 1 million IPs and mac addresses and 1024 ports, the Group By operation has to look at every combination of those values which is... 10^15 (too many). So you'll want to limit the number of results in each of the `Rows` queries in some way. Unfortunately Pilosa doesn't currently have a lot of built in ways to do that. You've got `previous`, `limit`, and the `column` argument. You might be able to hack column somehow by inserting some dummy data. Essentially the Rows query will only return rows which that column has set.

To answer your actual questions, millions of results is probably fine, billions will probably get to be too much. Very hardware and data dependent.

**Comment by young118** [comment]
@jaffee OK, I see, thanks very much
