### ISSUE TITLE
Clients should fail over to other nodes if one is down

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#293]
Clients should be aware of all the nodes in the cluster (by hitting an endpoint) and fail over to another node if the connection fails.

**Comment by jaffee** [comment]
@yuce similar to the consistent hash one, do you have any input on how we should organize these types of tickets.

**Comment by yuce** [comment]
@jaffee  I agree that client tickets should not be in the Pilosa server repo. Having the same ticket in different client libraries feels most appropriate considering the maintainers and users of those libraries would be different. But the problem is, who will create the tickets? Original ticket reporter or library maintainers ?

**Comment by yuce** [comment]
Since client library users would ticket bugs and feature requests in the client library they are using, probably other client library maintainers should copy the ticket to their repos if the bug/feature request is relevant.

**Comment by yuce** [comment]
Moved this ticket to: https://github.com/pilosa/python-pilosa/issues/40
