### ISSUE TITLE
Is it possible to safely remove old time quantums?

### ISSUE THREAD

**Issue by jarutis** [pilosa/pilosa#612]
Hi,

I wanted to know if it is possible to remove old data from index without reimporting all data. The use case is the following. I import data with YMD time quantum and I am only interested in last 30 days of data.

 - Do I get performance penalty for having data which is not out of Range query?
 - Is where a way to use TopN query for finding top intersections within specified Range (as I understand I can use Range for the bitset I'm intersecting with, but not for the frame)?
 - Can I just delete corresponding views from disk and expect everything to work?

Thanks for your answer,

Jonas

**Comment by travisturner** [comment]
Hey @jarutis,
Great questions!

First, if you're only interested in data from the last 30 days, you might consider defining the timeQuantum on your frame as either "D" or "DH" (depending on if you need hour granularity in your range queries). In your case there wouldn't be any reason to store "Y" or "M".

As far as removing old time quantums, you can't currently do that on a running Pilosa cluster. The only option, if you need to remove those, is to stop the Pilosa server, delete the appropriate view directories (`standard_20170607` for example), and restart Pilosa. The alternative is to leave those old time quantum directories there with the downsides being that they obviously take up space and they require additional open file handles, although there wouldn't be a performance penalty. 

With all that said, I'm going to open a new issue to allow users to remove old timeQuantums from a running Pilosa cluster via the API. Thanks for the suggestion!

Regarding your TopN question, I don't quite understand what you're trying to do. Can you provide an example?

**Comment by travisturner** [comment]
I opened #613 to address this.

**Comment by jarutis** [comment]
Thanks for quick answer!

I want to query TopN intersections for last 30 days only, so that rows with older timestamps would not be included in the bitsets.

For example:
TopN(Range(frame="segment", segment_id=37, start="2017-05-06T00:00", end="2017-06-06T00:00"), frame="domain", n=500)

Can I apply range to all the bitsets that I'm intersecting with in the `domain` frame?

This is not a big issue for me as i'll probably just delete old data.

**Comment by travisturner** [comment]
The example query that you gave is going to return the top 500 domains that have columns in common with the columns found for segment 37 over the last 30 days. It sounds like you're wanting to associate time to the domain as well, but in this case it's going to include domains from all time.

I think I understand what you're trying to do, but unfortunately you can't currently filter by time on a TopN query. I'll give some more thought on how we might achieve that because it seems like a useful function.

In the mean time—and it might be unreasonable depending on your use case—a heavy-handed way to approach this might be to write every setbit to 30 topN frames at once, where the newest frame represents "today" and the oldest frame represents "the last 30 days". All your read queries would need to go to the oldest frame, and that frame would effectively represent TopN over the last 30 days. Every day you could delete the oldest frame. I'm not necessarily advocating this—the write performance may not meet your requirements—but logically I think it achieves what you want.

**Comment by travisturner** [comment]
Closing this issue, but let me know if you have other question.
