### ISSUE TITLE
Some logs respect --log-path option and some do not

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#631]
### Expected behavior
If `--log-path=filename` is passed, all log output will go to `filename` and not stdout or stderr.

### Actual behavior
This goes to the log file:
```
2017/06/12 15:14:38 holder sync monitor initializing (10m0s interval)
```

This goes to stdout or stderr:
```
Pilosa v0.4.0-12-g74553d8, build time 2017-06-12T15:14:33+0000
Using data from: /home/ubuntu/pilosa/data1
Listening as http://node1.jaffee28.sandbox.pilosa.com:10101
```

### Steps to reproduce the behavior
`pilosa server --log-path=somefile` 
Then see what goes to the file, and what goes to your terminal.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Happens on linux and osx, both cluster and single node.

**Comment by travisturner** [comment]
I took a first pass at this just to ensure that `--log-path` is honored.
The work is in a WIP commit here: https://github.com/travisturner/pilosa/tree/logger
I'll take another pass at the logger logic to see if I can make setup a little cleaner, and also to avoid creating new loggers on every log line due to this pattern:
```
func (s *Struct) logger() *log.Logger { return log.New(s.LogOutput, "", log.LstdFlags) }
```
