### ISSUE TITLE
Use 16 bit ints instead of 32 in array and rle containers

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#664]
### Description
We currently use uint32 for array and rle containers in the roaring implementation, despite all values fitting in to uint16. Using uint16 should reduce the amount of storage used, and may boost performance.

### Success criteria (What criteria will consider this ticket closeable?)
uint16 are used instead of uint32 and storage is reduced.

**Comment by ramasLTU** [comment]
Hi, could You please elaborate a little on what could this change mean for the feature set of Pilosa? Would that affect the bit range that can be passed to Pilosa? Or is it just some internal optimisation, which will not impose any new restrictions?
The worry and the reason behind this question is that Pilosa does not support int64 bits already, which are pretty common storage type for users in AdTech. Hashing to int32 bits is also not an option, since Pilosa does not work well with sparse numbers (#591). This forces maintaining of user ID dictionaries, which can be overwhelming when big amounts of data are being processed, especially when you consider very short life-time of noted IDs.

**Comment by alanbernstein** [comment]
This will not affect Pilosa features. It is an internal change to reduce the storage size of segments of bitmaps (containers, in roaring terminology) that are run-length encoded. Each of these containers is associated with a key for the 48 high bits (common to all elements in the container). The container itself stores the low 16 bits.

**Comment by ramasLTU** [comment]
Thank you for clarifying.
