### ISSUE TITLE
Adding node in a cluster

### ISSUE THREAD

**Issue by vivekkumar159** [pilosa/pilosa#703]
Hi, I want to know lets say we have a cluster having one node and if i want to add one more node to the cluster. So just by doing --cluster.hosts="host1, host2", will the new node be added to current cluster or for adding the new node we need to setup the whole cluster again ?
Thanks

**Comment by travisturner** [comment]
Hi @vivekkumar159 
Currently you need to set up a new cluster in order to scale up (or down) the number of nodes in the cluster. Pilosa doesn't automatically rebalance the data across that cluster, although this is definitely on our short-term roadmap.

With that said, there are a couple of manual options that you have if you want to avoid rebuilding the cluster from scratch. Note that both require you to stop the pilosa server.
- Move the data files to the appropriate node. Data files are assigned to a node in the cluster based on a consistent hash algorithm using a key made up of index name and slice value. You can determine which node should contain each data fragment by following the logic in [FragmentNodes()](https://github.com/pilosa/pilosa/blob/master/cluster.go#L214). An example of the data files to be moved are the files `myindex/myframe/views/standard/fragments/0` and `myindex/myframe/views/standard/fragments/0.cache`, which contain the data for slice `0` in index `myindex`.
- In the case where you're moving from a 1-node to a 2-node cluster, and you aren't concerned about disk space, you could copy the entire Pilosa data directory to the second node, not worrying about the consistent hash logic at all, and then start both servers. This would result in data files that are no longer used residing on both servers, but it wouldn't affect performance.

**Comment by jaffee** [comment]
Closing as this functionality is covered by #737 (WIP). Please feel free to re-open or open a new ticket if there are further issues not covered by that.
