### ISSUE TITLE
Set operation calls do not return attributes

### ISSUE THREAD

**Issue by yuce** [pilosa/pilosa#787]
### Expected behavior

`Union`, `Intersect` and `Difference` calls return attributes corresponding to the bits in the result.

### Actual behavior

No attributes are returned.

### Steps to reproduce the behavior

```
SetBit(frame="f", rowID=1, columnID=100)
SetRowAttrs(frame="f", rowID=1, foo="bar")
Union(Bitmap(frame="f", rowID=1), Bitmap(frame="f", rowID=1))
```

returns: 
```
{
  "results": [
    {
      "attrs": {},
      "bits": [
        100
      ]
    }
  ]
}
```

**Comment by travisturner** [comment]
@yuce I'm not sure I understand the request here. Your example provides row attributes, but mentions the bits in the result (which are columns). The reason why we don't return row attributes in a complex query is because it's not clear which attributes you would want returned. For example, if your query is `Union(Bitmap(frame="f", rowID=1), Bitmap(frame="f", rowID=2))`, do you want the attributes from any and all rows in the query?

If instead you want the column attributes corresponding to the bits in the result, you have to provide the `columnAttrs=true` query argument. If in your example you also run:
```
SetColumnAttrs(columnID=100, name="To Kill a Mockingbird", year=1960)
```
then a query to 
```curl -X POST "http://localhost:10101/index/i/query?columnAttrs=true" -d 'Union(Bitmap(frame="f", rowID=1), Bitmap(frame="f", rowID=1))'
```
 will return:
```
{"results":[{"attrs":{},"bits":[100]}],"columnAttrs":[{"id":100,"attrs":{"name":"To Kill a Mockingbird","year":1960}}]}
```

**Comment by yuce** [comment]
My thinking was `Union(Bitmap(frame="f", rowID=1), Bitmap(frame="f", rowID=2))` would return all attributes for row 1 & 2 (instead of the user doing that on the client side). But implementing that would probably not worth the effort without a clear use case. Closing the issue.
