### ISSUE TITLE
Unbounded BSI fields

### ISSUE THREAD

**Issue by jaffee** [pilosa/pilosa#893]
### Description
When ingesting new data, it is often unknown ahead of time what range of values an integer might take. It would be convenient if one could create a BSI field without specifying a range up front. As values came in, the field would add rows to itself as necessary.

This flexibility would allow people to write less code/configuration for ingesting data.

Because ranges can start and end anywhere in positive or negative integers, we'd have to make some initial assumptions about the field, and have the ability to re-arrange things if necessary.

### Success criteria (What criteria will consider this ticket closeable?)
Not needing to define field ranges ahead of time when defining BSI fields.

**Comment by jaffee** [comment]
Per conversation with @travisturner today:

We should be able to move the not-null bitmap to position 0, then, if we assume a minimum value for each field, we should be able to add new bitmaps to increase the maximum value as needed.

The case where the minimum value changes is trickier as existing data would need to be rewritten - the majority of use cases would probably be supported fairly well by assuming 0 for positive values and some large negative number (-2**31)? for negative values.

**Comment by jaffee** [comment]
We just discussed this IRL. Is it possible to treat all fields as being based on -intMax and then track the actual min and max, and optimize queries based on which rows you know are going to be all 0 or all 1 based on the min and max. 

Not sure how well this would work, needs to be thought about.

**Comment by travisturner** [comment]
I don't think basing the range on `-intMax` will work.

If we look at an 8-bit version, the values would be represented as:
```
  -128 -127 ... -1   0   1 ... 126  127
0   -    1       1   -   1      -   1
1   -    -       1   -   -      1   1
2   -    -       1   -   -      1   1
3   -    -       1   -   -      1   1
4   -    -       1   -   -      1   1
5   -    -       1   -   -      1   1
6   -    -       1   -   -      1   1
7   -    -       -   1   1      1   1
```

If I assume that everything is based off `-intMax = -128`, then setting two columns with `field = -1` and `field = 1` will set a bit in every row. In that example, even though the effective min/max range is [-1,1], we are using all 8 rows to represent that range (instead of 2 rows).

I think it's reasonable to dynamically grow the range in one direction (i.e. above the max), but changing the min would require rewriting data.

**Comment by seebs** [comment]
Design idea: I think we'd want to start with "make the presence bit be the first bit", because that way we can handle an unbounded range.

Currently, we're specifying min/max, which translate into offset (min) and range (max-min). If you ever want to store a value under the minimum, you have to rewrite everything.

If we specify the presence bit first, we can grow the number of bits used. We then face the question: What range of bits do we read when checking things, or what range of bits do we set when overwriting an existing value? So we probably need to stash a field-wide "maximum value seen".

We could also use a sign-magnitude representation. This does cost an extra bit per entry, for at least some common cases, but gives a lot of generality. We can still use the offset to reduce the number of bits written. For instance, if you wanted to store years in a field, instead of specifying a range of years, you specify a base year and compute everything as offsets.

So in the current system, if you want to specify birth-years, you have to do the thing web sites do and guess at a possible range. So you specify, say, 1937-2020. But of course, your system might be in use longer, so maybe 1937-2038. (We don't care about 2039, because the `time_t`s will have wrapped and everyone will be dead.) So that's 101 years, so we end up with a 7-bit range plus a presence bit, so we use 8 bits of storage, but if we get a value outside that range, we can't represent it.

In my theoretical system, you pick a likely midpoint year, say, 2000. You always have a presence bit and a sign bit. If all your users are born in 2000, exactly, we're actually done -- we never end up writing any value bits. If all your users are born between 1999 and 2001, we express everything with a single value bit. With 6 value bits, we can represent everything from 1937-2063, instead of 1937-2064. But if we get a user born in 1930, or 2070, we just add a bit to the field, we don't have to rewrite everything.

This is not a compatible representation, it would be a new field type.

**Comment by benbjohnson** [comment]
One option that I believe would be backwards compatible would be to use sign extension and add bitmaps as the required number of bits increases. It's the same idea as when you cast an `int8` into an `int16` in Go except that in Pilosa it might just be an `int8` to an `int9`.

For example, here is the conversion of `-10` and `10` using sign extension (https://play.golang.org/p/fH4pl1XX8OW):

```
int8(-10):          11110110
int16(-10): 1111111111110110

int8(10):           00001010
int16(10):  0000000000001010
```

It just takes the MSB and repeats it for all the new bits.

So for Pilosa, if we need to move from storing 8-bit values to 10-bit values then we can simply copy the 8th bitmap in the BSI into the 9th and 10th bitmap and we won't need to rewrite any values.

We can still use the `min` field since that'll just be the offset. (We may want to rename it though) The `max` field becomes irrelevant though since we can always add more bits.

Would that work?

**Comment by seebs** [comment]
The hard part, I think, is the existence bits, which are currently stored immediately after the highest bit, so we'd currently need to copy the 9th bit to the 11th, then copy the 8th to the 9th and 10th. So swapping to have presence bit first would simplify life. Hmm. I could see working with 2s-complement and sign extension also working, but the downside is that small negative numbers still need all their higher-order bits set, so we have to create a lot more bits. Sign-magnitude would let us extend the range without having to modify or add bits to the existing values. (Which might be a bonus; for a large data set, it becomes possible to fail partway through updating the field, and then it's very hard to tell which values were updated and which weren't.)

**Comment by benbjohnson** [comment]
Yeah, I think the existence bit should probably get moved out of the last bit. That seems like a relatively quick and simple migration operation.

I see what you’re saying about sign magnitude. Do query operations become more complicated? e.g. would the Sum() operation would be the sum of the set of positive numbers minus the set of negative numbers? Maybe the performance difference would be minimal anyway.

**Comment by seebs** [comment]
I think for sign-magnitude, the simplest thing is to just compute the value of the non-sign-bit part of the field the same way we do now, then either multiply by -1 or choose between add and subtract based on the sign bit? I doubt the performance cost of any likely computation will be measurable. I don't even think the branch cost would likely be noticeable, but if it really was, `x * 1 - (signBit << 1)` is branchless, whee.

**Comment by jaffee** [comment]
I love this discussion.

I think the ability to have arbitrarily sized integers that can easily increase their supported range will help support more varied workloads and be a cool differentiator. I especially love that we get odd-sized ints essentially for free and that they can be increased as necessary without any extra data movement - what other data system does that?

I'm not too concerned about backwards compatibility if we have to break it (and do a 2.0) or add a new field type and deprecate the existing ints, I think this functionality is worth it.

I am a little bit concerned about how sign-magnitude affects the query logic - do we effectively double the number of logical ops we have to do to serve e.g. a Range query that spans positive and negative?  I *think* it's more of an n+1 situation but I'd have to dig in more to be sure.
