### ISSUE TITLE
range query out of memory 

### ISSUE THREAD

**Issue by yuzhichang** [pilosa/pilosa#939]
I have a benchmark of pilosa range query.
[pilosa_range_bench.go.txt](https://github.com/pilosa/pilosa/files/1453566/pilosa_range_bench.go.txt)

It inserts 1M documents into bitmap, then query. The insertion phase costs about 90s. At query phase, it crash due to out-of-memory.

My laptop is running Linux Mint 18.2, amd64, 8GB RAM + 8GB Swap.

GC log indicates heap keeps increasing:

```
gc 12398 @119.833s 1%: 0.007+2404+0.099 ms clock, 0.058+0.043/0.40/2404+0.79 ms cpu, 2872->2872->2119 MB, 3391 MB goal, 8 P
gc 12399 @124.688s 1%: 0.008+4985+0.087 ms clock, 0.067+0.14/0.078/4985+0.70 ms cpu, 5429->5429->3310 MB, 5430 MB goal, 8 P
gc 12400 @129.720s 1%: 23+7088+0.14 ms clock, 185+0.16/1.9/7186+1.1 ms cpu, 5609->5609->4138 MB, 6621 MB goal, 8 P
scvg0: inuse: 7014, idle: 1201, sys: 8216, released: 0, consumed: 8216 (MB)

```

Memory profile indicates almost all heap space is allocated by a single line.

```
(pprof) list RunBitmap
Total: 3.23GB
ROUTINE ======================== github.com/pilosa/pilosa/roaring.differenceRunBitmap in /home/zhichyu/src/github.com/pilosa/pilosa/roaring/roaring.go
    3.23GB     3.23GB (flat, cum)   100% of Total
         .          .   2523:				} else if bit == run.last {
         .          .   2524:					run.last--
         .          .   2525:				} else {
         .          .   2526:					run.last = bit - 1
         .          .   2527:					if run.last >= run.start {
    3.23GB     3.23GB   2528:						output.runs = append(output.runs, run)
         .          .   2529:					}
         .          .   2530:					run.start = bit + 1
         .          .   2531:					run.last = a.runs[j].last
         .          .   2532:				}
         .          .   2533:				if run.start > run.last {
(pprof) 

```

I have patched pilosa with following diff to resolve a segment fault:
```
diff --git a/roaring/roaring.go b/roaring/roaring.go
index 62f87d9..c05d9e6 100644
--- a/roaring/roaring.go
+++ b/roaring/roaring.go
@@ -2508,7 +2508,7 @@ func differenceRunArray(a, b *container) *container {
 // differenceRunBitmap computes the difference of an run from a bitmap.
 func differenceRunBitmap(a, b *container) *container {
        // If a is full, difference is the flip of b.
-       if a.runs[0].start == 0 && a.runs[0].last == 65535 {
+       if len(a.runs) > 0 && a.runs[0].start == 0 && a.runs[0].last == 65535 {
                return b.flipBitmap()
        }
        output := &container{container_type: ContainerRun}


```

pilosa revision:
```
zhichyu@wonder:~/src/github.com/pilosa/pilosa$ git log
commit bbc82d166dad8c3d033f8b46d37553ec02dea44a
Merge: 17da044 64da894
Author: Michael Baird <raskle@yahoo.com>
Date:   Tue Nov 7 10:12:56 2017 -0600

```

**Comment by alanbernstein** [comment]
Hi @yuzhichang, thanks for the bug report!

Your patch is informative, but after applying it, I encountered other errors while querying, so we need to figure out the root cause. We have a couple people looking into this.

Is there a reason you're using importing Pilosa server code, rather than interacting with a running server via a client (such as https://github.com/pilosa/go-pilosa, or just curl)?

**Comment by yuzhichang** [comment]
Hi @alanbernstein , I'm integrating Pilosa server code to another [project](https://github.com/deepfabric/elasticell) to support range search.

**Comment by yingfeng** [comment]
@alanbernstein 
I think pilosa and [elasticell](https://github.com/deepfabric/elasticell) could benefit from each other..

We are going to adopt pilosa as the full text search module for elasticell, we use roaring bitmap for the inverted index as well as numeric filtering, since we don't care relevance computation which has occupied remarkable overhead within traditional indices such as lucene. Currently, elasticell is a standard multi-raft implementation for strong consistent distributed storage.  Given pilosa encapsulated, a cloud native analysis engine with high availability could be available.

**Comment by alanbernstein** [comment]
@yuzhichang We expanded on your patch here: https://github.com/pilosa/pilosa/pull/949 (now in master). After this fix, I am able to run your test code without trouble.

@yingfeng Elasticell looks interesting, and we would love to learn more about your use of Pilosa with it! If you have any other trouble let us know, and please share your progress.
